name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff Check (Linter)
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - name: Run Ruff Format (Formatter)
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

name: Clang Format Checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
        uses: RafikFarhad/clang-format-github-action@v6.0.1
        with:
          sources: "src/*.cpp,src/*.h"